version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5408:5432"
    environment:
      POSTGRES_DB: various_small_datasets
      POSTGRES_USER: various_small_datasets
      POSTGRES_PASSWORD: insecure
    volumes:
      - ./backups:/tmp/backups

  importer:
    image: docker-registry.data.amsterdam.nl/datapunt/various_small_datasets:${ENVIRONMENT}
#    build: ../..
    links:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: various_small_datasets
      DATABASE_USER: various_small_datasets
      DATABASE_PASSWORD: insecure
    command: >
      bash -c "python manage.py import_catalog &&
      ./datasets/biz/import/import.sh &&
      ./datasets/trm/import/import.sh &&
      ./datasets/hior/importer/import.sh &&
      ./datasets/iot/import/import.sh &&
      ./datasets/hoofdroutes/import/import.sh &&
      ./datasets/milieuzones/import/import.sh &&
      ./datasets/vezips/import/import.sh &&
      ./datasets/bekendmakingen/import/import.sh &&
      ./datasets/openbare-verlichting/import/import.sh &&
      ./datasets/parkeerzones/import/import.sh &&
      ./datasets/asbest/import/import.sh &&
      ./datasets/reclame/import/import.sh &&
      python manage.py import_generic"
# oplaadpalen is  in a special import
