version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5408:5432"
    environment:
      POSTGRES_DB: various_small_datasets
      POSTGRES_USER: various_small_datasets
      POSTGRES_PASSWORD: insecure
    volumes:
      - ./backups:/tmp/backups

  importer:
    image: repo.data.amsterdam.nl/datapunt/various_small_datasets:${ENVIRONMENT}
#    build: ../..
    links:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: various_small_datasets
      DATABASE_USER: various_small_datasets
      DATABASE_PASSWORD: insecure
    command: >
      bash -c "python manage.py import_catalog &&
      ./biz/import/import.sh &&
      ./trm/import/import.sh &&
      ./hior/importer/import.sh &&
      ./iot/import/import.sh &&
      ./hoofdroutes/import/import.sh &&
      ./milieuzones/import/import.sh &&
      ./vezips/import/import.sh &&
      ./bekendmakingen/import/import.sh &&
      ./openbare-verlichting/import/import.sh &&
      ./parkeerzones/import/import.sh &&
      python manage.py import_generic"
# oplaadpalen is  in a special import
